config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:create]
  resources :games, only: [:index, :show, :update] do
    resources :game_users, only: [:create]
  end
  root 'sessions#new'
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :game_users, dependent: :destroy
  has_many :users, through: :game_users
  belongs_to :winner, class_name: 'User', optional: true

  scope :pending, -> { where(started_at: nil) }
  scope :in_progress, -> { where.not(started_at: nil).where(ended_at: nil) }
  scope :finished, -> { where.not(started_at: nil).where.not(ended_at: nil) }

  def self.create_pending_games_if_needed
    (2..5).each do |player_count|
      if Game.pending.where(player_count: player_count).count.zero?
        Game.create(player_count: player_count)
      end
    end
  end

  def start
    return unless pending? && ready?

    go_fish = GoFish.new(create_players)
    go_fish.start
    update(game_state: go_fish.as_json, started_at: Time.zone.now)
  end

  def play_turn(player_name, card_rank)
    asked_player = players.find { |player| player.name == player_name }
    go_fish.play_turn(asked_player, card_rank)
    update(game_state: go_fish.as_json)
  end

  def pending?
    started_at.nil?
  end

  def ready?
    users.count == player_count
  end

  def create_players
    users.map { |user| Player.new(user.name, user.id) }
  end

  def go_fish
    @go_fish ||= GoFish.from_json(game_state)
  end

  def players
    go_fish.players
  end

  def deck
    go_fish.deck
  end

  def current_player
    go_fish.current_player
  end

  def winning_player
    return unless go_fish.winner

    update(winner_id: go_fish.winner.user_id, ended_at: Time.zone.now) if winner_id.nil?
    go_fish.winner.name
  end

  def state_for(user)
    state = go_fish.state_for(user_player(user))
    state['id'] = id
    state['winner'] = winning_player
    state
  end

  def user_player(user)
    players.find { |player| player.user == user }
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :update

  @@pusher_client = Pusher::Client.new(
    app_id: '610491',
    key: '656e007150142d5db2c4',
    secret: 'db5c4cb7e2cbff381984',
    cluster: 'us2',
    encrypted: true
  )

  def index
    Game.create_pending_games_if_needed
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
    if @game.pending?
      @game.start
      if @game.pending?
        render :waiting
      else
        redirect_to @game
      end
    else
      @game_state = @game.state_for(current_user)
      respond_to do |format|
        format.html
        format.json { render json: @game_state }
      end
    end
  end

  def update
    game = Game.find(params[:id])
    game.play_turn(params['selectedOpponentName'], params['rank'])
    @@pusher_client.trigger('go-fish', 'round-played', gameId: params[:id])
    game_state = game.state_for(current_user)
    respond_to do |format|
      # format.html { redirect_to game }
      format.json { render json: game_state }
    end
  end

  private

  def users_turn?(game)
    game.current_player.user == current_user
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.slim
- pending_games = @games.pending.sort_by(&:player_count)
- finished_games = @games.pending.sort_by(&:started_at)

.pending-games
  h1.center Pending Games
  ul
    - pending_games.each do |game|
      - content = "#{game.player_count} Player #{game.game_users.count}/#{game.player_count}"
      = button_to content, game_game_users_path(game)

  h2 Game history
  table
    tr
      th Game ID
      th Start Time
      th End Time
      th Winner
    - @games.finished.each do |game|
      tr class="#{game.winner_id == current_user.id ? 'winner' : 'loser'}"
        td #{game.id}
        td #{game.started_at}
        td #{game.ended_at}
        td #{game.winner.name}

app/views/games/play_turn.html.slim
- @user_player = @game.players.find { |player| player.user_id == current_user.id }
- @other_players = @game.players.reject { |player| player == @user_player }

= react_component('PlayTurn',
  player: @user_player,
  opponents: @other_players)

app/views/games/show.html.slim
= react_component('GameView',
    id: @game_state['id'],
    deckCount: @game_state['deckCount'],
    player: @game_state['player'],
    currentPlayer: @game_state['currentPlayer'],
    opponents: @game_state['opponents'],
    winner: @game_state['winner'])

app/views/games/waiting.html.slim
- player1 = @game.users.find { |user| user == current_user }
- other_players = @game.users.reject { |user| user == current_user }

h1 Waiting for more players
- other_players.each do |player|
  span.player = player.name
= player1.name